// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(QuestionaireDbContext))]
    partial class QuestionaireDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerId = 4,
                            Text = "ข้อใดต่างจากข้ออื่น"
                        },
                        new
                        {
                            Id = 2,
                            AnswerId = 6,
                            Text = "X + 2 = 4 จงหาค่า X"
                        });
                });

            modelBuilder.Entity("api.Models.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionId = 1,
                            Text = "3"
                        },
                        new
                        {
                            Id = 2,
                            QuestionId = 1,
                            Text = "5"
                        },
                        new
                        {
                            Id = 3,
                            QuestionId = 1,
                            Text = "9"
                        },
                        new
                        {
                            Id = 4,
                            QuestionId = 1,
                            Text = "11"
                        },
                        new
                        {
                            Id = 5,
                            QuestionId = 2,
                            Text = "1"
                        },
                        new
                        {
                            Id = 6,
                            QuestionId = 2,
                            Text = "2"
                        },
                        new
                        {
                            Id = 7,
                            QuestionId = 2,
                            Text = "3"
                        },
                        new
                        {
                            Id = 8,
                            QuestionId = 2,
                            Text = "4"
                        });
                });

            modelBuilder.Entity("api.Models.Respondent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Respondents");
                });
#pragma warning restore 612, 618
        }
    }
}
